### PR TITLE
Feature: strip ignored characters

### PR DESCRIPTION
**Pull request by rybon**
Adds an option that when enabled returns a stripped version of the GraphQL string literal instead of the AST object.

### CODE REVIEW

**Comment by rybon** [comment]
@gajus please review.

**Comment by gajus** [comment]
What is the use case?

**Comment by rybon** [comment]
The use case is compiling away any GraphQL overhead such as large AST objects or library import or even whitespace in the string literal so that the resulting production bundle is as small and light-weight as possible. It also saves on network bytes when actually performing the GraphQL calls.

**Comment by gajus** [comment]
The whole point of this library is to compile GraphQL queries into AST so that you wouldn't need to do that on the client-side. If you don't do this, then you need to add `graphql-tag` dependency, which is approx. 50KB.

**Comment by rybon** [comment]
But those ASTs are way larger than the string literals. Why would you want to embed them in a bundle? The queries in the source code are attached to the tagged template of `graphql-tag`, which means they are easier to work with (for example ESLint can scan for `gql` tags and lint the string literal), but in production those queries can just be inanimate strings (this is how they are sent to the GraphQL server anyway).

**Comment by gajus** [comment]
> Why would you want to embed them in a bundle? 

https://github.com/apollographql/graphql-tag#why-use-this

Either way, I am Okay with this feature.

**Comment by rybon** [comment]
Thanks, could you publish to NPM?

**Comment by randing89** [comment]
> The queries in the source code are attached to the tagged template of graphql-tag, which means they are easier to work with (for example ESLint can scan for gql tags and lint the string literal), but in production those queries can just be inanimate strings (this is how they are sent to the GraphQL server anyway).

This is not ture. `graphql-tag` is not just for local development. Apollo and react-apollo needs the AST of query if there are local resolvers being setup. What is being sent to server not always equal to what you wrote. There are transformation in the runtime depending on the setup. Changing it from AST to string will break users that has local resolvers or schema stitching.

The purpose of this library is pre-compile queries so we can save computation cost in the runtime. Essentially it is trading asset size over evaluation cost of parsing a query string.
However `strip` is still valuable I think because the compiled result contains the full source in `loc` field. Stripping them will reduce some size.

**Pull request merged**
