### PR TITLE
Allow single, unnamed, queries

### PR DESCRIPTION
**Pull request by nhunzaker**
Follow up to #3. This commit adds a guard to only validate a query name if there are multiple definitions.

I wanted to test the failure case, but I wasn't quite sure how to do it within the current testing setup.

### CODE REVIEW

**Comment by gajus** [comment]
> I wanted to test the failure case, but I wasn't quite sure how to do it within the current testing setup.

Just create a separate test file in `./test` and use mocha as you normally would.

**Comment by nhunzaker** [comment]
Cool. Done.

The try/catch here is making it hard to test for errors:
https://github.com/gajus/babel-plugin-graphql-tag/blob/master/src/index.js#L47-L56

I wrote a test that overrides `console.error` to assert the bad input. Just curious - why `console.error` instead of throwing?

**Comment by nhunzaker** [comment]
Hey again! It's totally fine if you're swamped, but I was wondering if there was anything I could do to make reviewing this easier. 

This isn't important for anything I'm working on, just wanted to check in.

**Comment by gajus** [comment]
Thank you chasing up. This left my radar.

**Comment by nhunzaker** [comment]
No worries, thanks!

**Pull request merged**
