### PR TITLE
Upgrade to Babel 7

### PR DESCRIPTION
**Pull request by milesj**
@gajus 

- Upgrades to Babel 7.
- Upgrades to GraphQL 14.
- Switches to Jest from Mocha since Babel's runner requires it.
- Integrated Yarn to take advantage of resolutions.
- Dropped Node 6.

### CODE REVIEW

**Comment by milesj** [comment]
Not sure how to resolve flow but eslint/jest pass.

Is flow necessary for the very few amount of types its using?

**Comment by gajus** [comment]
Fixed them.

Thank you.

**Comment by milesj** [comment]
@gajus Any chance of getting a 2.0 release?

**Comment by gajus** [comment]
Done

**Comment by milesj** [comment]
Thank you!

**Pull request merged**
